INSERT INTO burgers (burger_name, devoured) VALUES ("Royal Red Robin Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Black & Bleu Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Smoke & Pepper Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Sauteed 'Shroom Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Bacon Cheeseburger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Banzai Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Guacamole & Bacon Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Wedgie Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Veggie Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Citrus Harissa Salmon Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Crispy Artic Cod Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Grilled Turkey Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Marco Pollo Burger", false);
INSERT INTO burgers (burger_name, devoured) VALUES ("Bruschetta Chicken Burger", false);